require: rubocop-rails

AllCops:
  Exclude:
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
    
Metrics/LineLength:
  Max: 120

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/ActiveRecordAliases:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/UnknownEnv:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
